### ISSUE TITLE
Cocoapods, use_frameworks! option, and non-public class

### ISSUE THREAD

**Issue by spifd** [bvogelzang/SevenSwitch#30]
When used as a Cocoapods dependency with `use_frameworks!` option, I encounter a compilation issue with SevenSwitch class not being found. It looks like SevenSwitch must be made a `public` class to be exposed... do you confirm?

**Comment by ippy04** [comment]
:+1: Seeing the same - With use_frameworks! I'm able to see the control in Interface Builder if I specify SevenSwitch as both the module and the class, but I can't see to create an outlet in the viewcontroller.

**Comment by bvogelzang** [comment]
Thanks for letting me know. The problem should be fixed now. You'll probably have to re-install your pods in your project since I kept the same version number. Use the following commands in your project directory and you should be good to go. `rm -r Pods` then `pod install`

**Comment by ippy04** [comment]
Works great thanks for the quick fix!
