### ISSUE TITLE
[Swift newbee] Error when trying to compile with the Objective-C file

### ISSUE THREAD

**Issue by colasjojo** [bvogelzang/SevenSwitch#31]
I want to compile the project with the objective-C `ViewController.m`. What I did:
  - I removed the  `ViewController.swift` from the list of the files to compile
  - I add the  `ViewController.m` from the list of the files to compile

![capture d ecran 2015-03-31 a 14 44 02](https://cloud.githubusercontent.com/assets/4303814/6919093/68bc8614-d7b4-11e4-9e74-b64accbfd1b2.png)

I get this error:

```
clang: error: no such file or directory: '/Users/colas/Downloads/SevenSwitch-master 2/SevenSwitchExample/SevenSwitchExample/SevenSwitchExample-Prefix.pch'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1
```

Furthermore, I don't know how to import the `swift` file to the `.m` View Controller.

![capture d ecran 2015-03-31 a 14 44 54](https://cloud.githubusercontent.com/assets/4303814/6919118/99fe5fe0-d7b4-11e4-8b10-4c6e0b605aeb.png)

**Comment by bvogelzang** [comment]
I did not include `ViewController.m` in the project to be compiled. It's just there to give you an example of how to use `SevenSwitch` within obj-c code. You'll get the same exact example and result from compiling the project normally with `ViewController.swift`.

If you want to use a swift source file within obj-c code you simply need to add an import statement like `#import "SevenSwitchExample-Swift.h"`. Where the first part of the import statement is your project/module name (in this case it's `SevenSwitchExample`). You can see this at the top of `ViewController.m`. This will take care of providing access to the swift code you would like to use. Xcode will automatically create this file for you so just adding the import statement is all you need to do.

If you want to use an obj-c source file within swift code you need to create what's called a bridging header. More information can be found in the documentation from Apple. I would suggest you read through it to get a good sense of how to mix and match obj-c and swift source files.

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by colasjojo** [comment]
Thanks :+1:
