### ISSUE TITLE
Getting "Initializer does not override a designated initializer from its superclass" error

### ISSUE THREAD

**Issue by wjf3** [bvogelzang/SevenSwitch#37]
In a fresh install of SevenSwift 2.0 I'm getting an error here in SevenSwitch.swift:

override public init() {
        super.init(frame: CGRectMake(0, 0, 50, 30))
        
        self.setup()
    }

I saw some people saying change "override public" to "convenience" then "super" to "self" and doing that removes the errors but when I write the test documentation:

let mySwitch = SevenSwitch()

I still get "Use of unresolved identifier 'SevenSwitch'"

Any ideas on why this isn't working?

**Comment by rockylive** [comment]
```
convenience init() {
        self.init(frame: CGRectMake(0, 0, 50, 30))
        
        self.setup()
    }
```

Fixed the issue

**Comment by bvogelzang** [comment]
Will be updating to work with swift 2.0 shortly
