### ISSUE TITLE
Thumbview shadow is not correctly set when using autolayout and a different sizes from the default

### ISSUE THREAD

**Issue by lmdg** [bvogelzang/SevenSwitch#47]
Hi, it seems that if you use autolayout and a different frame size then the shadow is incorrectly drawn. This is probably because the shadow path is set on initialization and not in layoutSubviews().
The workaround I'm currently using is to set the initial frame's width and height to the ones used in the constraints since you really can't extend the class as most of the properties are internal.
Other than that it works great, thanks in advance.

**Comment by bvogelzang** [comment]
this has been fixed. Closing.
