### ISSUE TITLE
Podspec for SevenSwitch 2.0 requires iOS 8.0

### ISSUE THREAD

**Issue by geoffreywiseman** [bvogelzang/SevenSwitch#48]
The pod spec for SevenSwitch 2.0 requires iOS 8.0, although the README still talks about iOS 5.0

**Comment by bvogelzang** [comment]
Previous versions (without swift) support iOS 5.0 and above. I'll update to the readme to make this a bit more clear. Thanks!

**Comment by geoffreywiseman** [comment]
Yeah, that's basically what I want -- for the README to better reflect the reality.
