### ISSUE TITLE
Add SevenSwitch to Navigation Bar

### ISSUE THREAD

**Issue by ryantomlinson95** [bvogelzang/SevenSwitch#51]
I'm trying to add SevenSwitch into my navigation bar as the right bar item but I can't figure out how. Any help? (In Swift)

**Comment by iamtomcat** [comment]
You have to wrap it in a uibarbuttonitem

```
let switch = //initialize switch
rightBarButtonItem = UIBarButtonItem(customView: switch)
```

**Comment by bvogelzang** [comment]
I believe @iamtomcat is correct. Closing this for now. Add a comment to this issue if you are still having trouble doing this.
