### ISSUE TITLE
swift 3

### ISSUE THREAD

**Issue by RockySightingsApps** [bvogelzang/SevenSwitch#57]
can you please update this to swift 3?

**Comment by albertbori** [comment]
(and Swift 2.3, for those of us who can't migrate just yet)

**Comment by lfarah** [comment]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by andreyrd** [comment]
I have a fork that's updated to Swift 3
https://github.com/andreyrd/SevenSwitch/tree/swift3

`pod 'SevenSwitch', :git => 'https://github.com/andreyrd/SevenSwitch.git', :branch => 'swift3'`

**Comment by bvogelzang** [comment]
I've updated for Swift 3 and Xcode 8.1

**Comment by lfarah** [comment]
Thanks @bvogelzang. You're awesome! 🎉

**Comment by lfarah** [comment]
Also thanks @andreyrd!
